// Code generated by MockGen. DO NOT EDIT.
// Source: ./mock/service.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceInter is a mock of ServiceInter interface.
type MockServiceInter struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterMockRecorder
}

// MockServiceInterMockRecorder is the mock recorder for MockServiceInter.
type MockServiceInterMockRecorder struct {
	mock *MockServiceInter
}

// NewMockServiceInter creates a new mock instance.
func NewMockServiceInter(ctrl *gomock.Controller) *MockServiceInter {
	mock := &MockServiceInter{ctrl: ctrl}
	mock.recorder = &MockServiceInterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInter) EXPECT() *MockServiceInterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockServiceInter) Get(id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceInterMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceInter)(nil).Get), id)
}
